export type IRecord = {
    id: number;
    title: string;
    description: string;
    category: string[];
    primary_category: string;
    status: string[];
    primary_status: string;
    amount: number;
    quantity: number;
    price: number;
    rate: number;
    is_active: string[];
    primary_is_active: string;
    created_at: Date;
    updated_at: Date;
    attributes: string[];
    primary_attribute: string | null;
    level: string[];
    primary_level: string;
    priority: string[];
    primary_priority: string;
    code: string;
    group_id: number;
    first_names: string;
    last_names: string;
    tags: string[];
    primary_tag: string | null;
    meta: string[];
    primary_meta: string;
    comment: string;
}